### ISSUE TITLE
Array can't be accessed both statically and dynamically

### ISSUE THREAD

**Issue by yiqiaoc** [r3c/verse#12]
Verse fails to read array value **without error or exception** when the following scenario appears:
Dialect:
```
proposal =
{
    y[$i] = arr[$i]
    x = arr[0]
}
```
Json input:
```
{
    "arr": [3, 5]
}
```
Verse should support both static and dynamic access to array and notify the caller if something bad happens

**Comment by r3c** [comment]
I believe this is an error in a library you're using that depends on Verse, not Verse itself as it has no concept of "dynamic" or "static" arrays 🙂

**Comment by r3c** [comment]
Closing as this doesn't seem to be a Verse issue. Please feel free to reopen if you can reproduce this using Verse code.
